### ISSUE TITLE
Code is unlicensed

### ISSUE THREAD

**Issue by timstaley** [pmelchior/pygmmis#2]
Hi @pmelchior,

great paper and your code looks really useful, I'm excited about trying to apply this for classification in  transient astronomy.

However, I just realized you haven't stated a license. I'm guessing this is an oversight (since the readme mentions to 'cite the paper if you use the code') but it effectively implies the code is "look, don't touch without explicit permission" in its current state. BSD, MIT, Apache, or GPL would be great :)

Cheers! 
-Tim

**Comment by pmelchior** [comment]
You're right, this is an oversight. I license all my codes as MIT (unless prevented by other constraints). This one will be properly licensed, too.
